name: gen

on:
  workflow_dispatch: # This allows the workflow to be run manually from the GitHub Actions UI
  schedule:
    - cron: "0 0 * * *" # Run every midnight

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This is required to push changes later

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script 100 times
        run: |
          for i in {1..100}; do
              python python.py
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add codes.txt
          git commit -m "Update code links"
          git -c http.extraheader="AUTHORIZATION: basic ${{ secrets.GTOKEN }}" push
        env:
          GTOKEN: ${{ secrets.GTOKEN }}
