name: test generation

on:
  workflow_dispatch: # This allows the workflow to be run manually from the GitHub Actions UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This is required to push changes later

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script 1 time
        run: |
          python python.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add proxy_list.txt
          git commit -m "Update code links"
          git -c http.extraheader="AUTHORIZATION: basic ${{ secrets.GIT_TOKEN }}" push
        env:
          GTOKEN: ${{ secrets.GIT_TOKEN }}
